service: serverless-mongodb-node

custom:
  region:
    dev: us-east-1
    prod: ap-south-1

  profile:
    dev: personal
    prod: personal

  deploymentBucket:
    dev: modern-workshop-bucket

package:
  individually: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profile.${self:provider.stage}}
  region: ${self:custom.region.${self:provider.stage}}
  deploymentBucket: ${self:custom.deploymentBucket.${self:provider.stage}}
  environment:
    DB_CONN_STRING: ${env:DB_CONN_STRING}

functions:
  - ${file(src/functions/user/index.yml)}
